matrix:
  VERSION:
    - 3.1
    - 3.2
    - 3.3

build:
  image: armhfbuild/docker:1.9.1-dind
  privileged: true
  commands:
    - docker daemon -s overlay -g /drone/docker &
    - apk add --update bash
    - ./build versions/library-$$VERSION/options

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: versions/library-$$VERSION/Dockerfile
    context: versions/library-$$VERSION
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/alpine
    tag: "$$VERSION"
    storage_driver: overlay

cache:
  mount:
    - /drone/docker
