matrix:
  VERSION:
    - 3.1
    - 3.2
    - 3.3

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    # FIXME Replace this hack when there is a real Docker build plugin
    - docker daemon -s aufs -g /drone/docker &
    - sleep 2
    - docker daemon -s overlay -g /drone/docker &
    - sleep 2
    - apk add --update bash
    - ./build versions/library-$$VERSION/options

publish:
  docker_3.1:
    image: armhfplugins/drone-docker:docker-caching
    file: versions/library-$$VERSION/Dockerfile
    context: versions/library-$$VERSION
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/alpine
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    when:
      matrix:
        VERSION: 3.1

  docker_3.2:
    image: armhfplugins/drone-docker:docker-caching
    file: versions/library-$$VERSION/Dockerfile
    context: versions/library-$$VERSION
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/alpine
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    when:
      matrix:
        VERSION: 3.2

  docker_3.3:
    image: armhfplugins/drone-docker:docker-caching
    file: versions/library-$$VERSION/Dockerfile
    context: versions/library-$$VERSION
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/alpine
    tag:
      - "$$VERSION"
      - latest
    force_tag: true
    storage_driver: overlay
    when:
      matrix:
        VERSION: 3.3

cache:
  mount:
    - /drone/docker
